- name: remove existing cert_info directory
  ansible.builtin.file:
    path: /tmp/cert_info
    state: absent

- name: recreate working directory
  ansible.builtin.file:
    path: /tmp/cert_info
    state: directory
