- name: remove existing cert_info directory
  ansible.builtin.file:
    path: /tmp/cert_info
    state: absent

- name: recreate working directory
  ansible.builtin.file:
    path: /tmp/cert_info
    state: directory

- name: to get the list of certificates
  ansible.builtin.shell: cd /etc/pki/tls/certs && ll >> /tmp/cert_info/cert_list
