- name: remove existing cert_info directory
  ansible.builtin.file:
    path: /tmp/cert_info
    state: absent

- name: recreate working directory
  ansible.builtin.file:
    path: /tmp/cert_info
    state: directory

- name: List certificates
  shell: ls -ltr /etc/pki/tls/certs >> /tmp/cert_info/cert_list

#- name: to get the list of certificates
#  ansible.builtin.find:
#    paths: /etc/pki/tls/certs
#    patterns: "*.crt"
#    recurse: yes
#  register: cert_files

#- name: To print cert_files
#  debug:
#    var: cert_files

#- name: To create customcertlog file
#  file:
#    path: /tmp/customcert.log
#    mode: '0644'
#    state: directory
#  ignore_errors: yes

#- name: Extract details from each certificate
#  shell:
#    cert_name=$(basename {{ item.path }})
#    cert_expiry=$(openssl x509 -in {{ item.path }} -noout -enddate | cut -d= -f2)
#    cert_san=$(openssl x509 -in {{ item.path }} -noout -ext subjectAltname | cut -d= f2 | tr -d '\n\' | sed 's/,/ /g')
#    echo "Cert Name: $cert_name" >> /tmp/customcert.log
#  loop: "{{ cert_files.files }}"
#  when: cert_files.matched > 0
#  register: cert_details


#
#- name: Extract certname details
#  shell:
#    cert_name=$(basename {{ item.path }})
#  loop: "{{ cert_files.files }}"
#  register : cert_name_output
#
#- name: To print cert_name
#  debug:
#    var: cert_name_output




