- name: To list certificates
  shell: find /etc/pki/tls/certs -name "*.crt" -exec basename {} \;
  register: cert_list

- name: Extract Expiry date of certificate
  shell: "openssl x509 -in /etc/pki/tls/certs/{{ item }} -noout -enddate | cut -d= -f2"
  register: expiry_date
  loop: "{{ cert_list.stdout_lines }}"

- name: Extract Serial Number of certificate
  shell: "openssl x509 -in /etc/pki/tls/certs/{{ item }} -noout -serial | cut -d= -f2"
  register: serial_number
  loop: "{{ cert_list.stdout_lines }}"

- name: Create custom.log file
  blockinfile:
    path: /tmp/custom.log
    block: |
      {% for cert in cert_list.stdout_lines %}
      Certificate_Name: {{ cert }}; Expiry: {{ expiry_date.results[loop.index0].stdout }}; Serial_Number: {{ serial_number.results[loop.index0].stdout }}
      {% endfor %}
    create: yes
    state: present