#- name: remove temporary folder before job starts
#  ansible.builtin.file:
#    state: absent
#    path: /tmp/cert_info

- name: recreate temporary folder
  ansible.builtin.file:
    state: directory
    path: /tmp/cert_info
    mode: '0644'